<?php

namespace App\Services\Ip2location;

final class RegionConverter
{
    public function getCodeByName(string $countryCode, string $name): ?string
    {
        return $this->codes()[$countryCode][$name] ?? null;
    }

    private function codes(): array
    {
        return [
            'RU' => [
                'Adygeya, Respublika' => 'RU-AD',
                'Altay, Respublika' => 'RU-AL',
                'Altayskiy kray' => 'RU-ALT',
                "Amurskaya oblast'" => 'RU-AMU',
                "Arkhangel'skaya oblast'" => 'RU-ARK',
                "Astrakhanskaya oblast'" => 'RU-AST',
                'Bashkortostan, Respublika' => 'RU-BA',
                "Belgorodskaya oblast'" => 'RU-BEL',
                "Bryanskaya oblast'" => 'RU-BRY',
                'Buryatiya, Respublika' => 'RU-BU',
                'Chechenskaya Respublika' => 'RU-CE',
                "Chelyabinskaya oblast'" => 'RU-CHE',
                'Chukotskiy avtonomnyy okrug' => 'RU-CHU',
                'Chuvashskaya Respublika' => 'RU-CU',
                'Dagestan, Respublika' => 'RU-DA',
                'Ingushetiya, Respublika' => 'RU-IN',
                "Irkutskaya oblast'" => 'RU-IRK',
                "Ivanovskaya oblast'" => 'RU-IVA',
                'Kabardino-Balkarskaya Respublika' => 'RU-KB',
                "Kaliningradskaya oblast'" => 'RU-KGD',
                'Kalmykiya, Respublika' => 'RU-KL',
                "Kaluzhskaya oblast'" => 'RU-KLU',
                'Kamchatskiy kray' => 'RU-KAM',
                'Karachayevo-Cherkesskaya Respublika' => 'RU-KC',
                'Kareliya, Respublika' => 'RU-KR',
                "Kemerovskaya oblast'" => 'RU-KEM',
                'Khabarovskiy kray' => 'RU-KHA',
                'Khakasiya, Respublika' => 'RU-KK',
                'Khanty-Mansiyskiy avtonomnyy okrug' => 'RU-KHM',
                "Kirovskaya oblast'" => 'RU-KIR',
                'Komi, Respublika' => 'RU-KO',
                "Kostromskaya oblast'" => 'RU-KOS',
                'Krasnodarskiy kray' => 'RU-KDA',
                'Krasnoyarskiy kray' => 'RU-KYA',
                "Kurganskaya oblast'" => 'RU-KGN',
                "Kurskaya oblast'" => 'RU-KRS',
                "Leningradskaya oblast'" => 'RU-LEN',
                "Lipetskaya oblast'" => 'RU-LIP',
                "Magadanskaya oblast'" => 'RU-MAG',
                'Mariy El, Respublika' => 'RU-ME',
                'Mordoviya, Respublika' => 'RU-MO',
                "Moskovskaya oblast'" => 'RU-MOS',
                'Moskva' => 'RU-MOW',
                "Murmanskaya oblast'" => 'RU-MUR',
                'Nenetskiy avtonomnyy okrug' => 'RU-NEN',
                "Nizhegorodskaya oblast'" => 'RU-NIZ',
                "Novgorodskaya oblast'" => 'RU-NGR',
                "Novosibirskaya oblast'" => 'RU-NVS',
                "Omskaya oblast'" => 'RU-OMS',
                "Orenburgskaya oblast'" => 'RU-ORE',
                "Orlovskaya oblast'" => 'RU-ORL',
                "Penzenskaya oblast'" => 'RU-PNZ',
                'Permskiy kray' => 'RU-PER',
                'Primorskiy kray' => 'RU-PRI',
                "Pskovskaya oblast'" => 'RU-PSK',
                "Rostovskaya oblast'" => 'RU-ROS',
                "Ryazanskaya oblast'" => 'RU-RYA',
                'Saha, Respublika' => 'RU-SA',
                "Sakhalinskaya oblast'" => 'RU-SAK',
                "Samarskaya oblast'" => 'RU-SAM',
                'Sankt-Peterburg' => 'RU-SPE',
                "Saratovskaya oblast'" => 'RU-SAR',
                'Severnaya Osetiya, Respublika' => 'RU-SE',
                "Smolenskaya oblast'" => 'RU-SMO',
                "Stavropol'skiy kray" => 'RU-STA',
                "Sverdlovskaya oblast'" => 'RU-SVE',
                "Tambovskaya oblast'" => 'RU-TAM',
                'Tatarstan, Respublika' => 'RU-TA',
                "Tomskaya oblast'" => 'RU-TOM',
                "Tul'skaya oblast'" => 'RU-TUL',
                "Tverskaya oblast'" => 'RU-TVE',
                "Tyumenskaya oblast'" => 'RU-TYU',
                'Tyva, Respublika' => 'RU-TY',
                'Udmurtskaya Respublika' => 'RU-UD',
                "Ul'yanovskaya oblast'" => 'RU-ULY',
                "Vladimirskaya oblast'" => 'RU-VLA',
                "Volgogradskaya oblast'" => 'RU-VGG',
                "Vologodskaya oblast'" => 'RU-VLG',
                "Voronezhskaya oblast'" => 'RU-VOR',
                'Yamalo-Nenetskiy avtonomnyy okrug' => 'RU-YAN',
                "Yaroslavskaya oblast'" => 'RU-YAR',
                "Yevreyskaya avtonomnaya oblast'" => 'RU-YEV',
                "Zabaykal'skiy kray" => 'RU-ZAB',
            ],
            'US' => [
                'Alabama' => 'US-AL',
                'Alaska' => 'US-AK',
                'Arizona' => 'US-AZ',
                'Arkansas' => 'US-AR',
                'California' => 'US-CA',
                'Colorado' => 'US-CO',
                'Connecticut' => 'US-CT',
                'Delaware' => 'US-DE',
                'District of Columbia' => 'US-DC',
                'Florida' => 'US-FL',
                'Georgia' => 'US-GA',
                'Hawaii' => 'US-HI',
                'Idaho' => 'US-ID',
                'Illinois' => 'US-IL',
                'Indiana' => 'US-IN',
                'Iowa' => 'US-IA',
                'Kansas' => 'US-KS',
                'Kentucky' => 'US-KY',
                'Louisiana' => 'US-LA',
                'Maine' => 'US-ME',
                'Maryland' => 'US-MD',
                'Massachusetts' => 'US-MA',
                'Michigan' => 'US-MI',
                'Minnesota' => 'US-MN',
                'Mississippi' => 'US-MS',
                'Missouri' => 'US-MO',
                'Montana' => 'US-MT',
                'Nebraska' => 'US-NE',
                'Nevada' => 'US-NV',
                'New Hampshire' => 'US-NH',
                'New Jersey' => 'US-NJ',
                'New Mexico' => 'US-NM',
                'New York' => 'US-NY',
                'North Carolina' => 'US-NC',
                'North Dakota' => 'US-ND',
                'Ohio' => 'US-OH',
                'Oklahoma' => 'US-OK',
                'Oregon' => 'US-OR',
                'Pennsylvania' => 'US-PA',
                'Rhode Island' => 'US-RI',
                'South Carolina' => 'US-SC',
                'South Dakota' => 'US-SD',
                'Tennessee' => 'US-TN',
                'Texas' => 'US-TX',
                'Utah' => 'US-UT',
                'Vermont' => 'US-VT',
                'Virginia' => 'US-VA',
                'Washington' => 'US-WA',
                'West Virginia' => 'US-WV',
                'Wisconsin' => 'US-WI',
                'Wyoming' => 'US-WY',
            ],
        ];
    }
}
